{application,cld,
             [{description,[]},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{cld_app,[]}},
              {env,[]},
              {modules,[cld,cld_app,cld_manager,cld_stats,cld_sup,
                        cld_websocket_handler,cld_worker,cld_worker_sup]}]}.
